urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.urls.conf import path

from bioshareX.forms import (BioshareAuthenticationForm,
                             BiosharePasswordResetForm)

admin.autodiscover()
# ***HACKY***  Monkey patching the authentication form so that the username field says email instead.
from django.contrib.auth.forms import AuthenticationForm
# from registration.forms import RegistrationFormUniqueEmail
# from bioshareX.forms import RegistrationForm, SetPasswordForm
# from registration.backends.default.views import RegistrationView
from django.contrib.auth.views import (  # , login, password_reset_confirm, password_reset
    LoginView, PasswordResetView, logout_then_login)

from bioshareX import views as bioshare_views

from django_ratelimit.decorators import ratelimit, UNSAFE

AuthenticationForm.base_fields['username'].label = 'Email' 


urlpatterns = [
    # Examples:
    # Uncomment the admin/doc line below to enable admin documentation:
    # re_path(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^bioshare/', include('bioshareX.urls')),
    re_path(r'^accounts/logout/$', logout_then_login, name='logout'),
    # path('accounts/login/', LoginView.as_view(authentication_form=BioshareAuthenticationForm), name='login',kwargs={'authentication_form':BioshareAuthenticationForm}),
    path('accounts/password_reset/', ratelimit(key='user_or_ip', rate='5/h', method=UNSAFE)(PasswordResetView.as_view(form_class=BiosharePasswordResetForm)), name='password_reset', kwargs={'password_reset_form':BiosharePasswordResetForm,'extra_email_context':{'SITE_URL':settings.SITE_URL}}),
#     re_path(r'^accounts/password_reset/$', password_reset, name='password_reset', kwargs={'password_reset_form':BiosharePasswordResetForm,'extra_email_context':{'SITE_URL':settings.SITE_URL}}),
    path('accounts/login/', ratelimit(key='post:username', rate='10/h', method=UNSAFE)(ratelimit(key='user_or_ip', rate='10/h', method=UNSAFE)(LoginView.as_view(authentication_form=BioshareAuthenticationForm))), name='login',kwargs={'authentication_form':BioshareAuthenticationForm}),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^$', bioshare_views.list_shares, name='home'),
    re_path(r'^Data/(?P<id>[\da-zA-Z]{10})/(?:(?P<subpath>.*/?))?$', bioshare_views.redirect_old_path, name='redirect_old_path'),
]

bioshareX/models.py
import os
import re
import subprocess

from django.conf import settings
from django.contrib.auth.models import Group, User
from django.contrib.postgres.fields.array import ArrayField
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_delete, post_save, pre_save
from django.dispatch import receiver
from django.urls.base import reverse
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.html import strip_tags
from guardian.models import GroupObjectPermissionBase, UserObjectPermissionBase
from jsonfield import JSONField
from bioshareX.exceptions import IllegalPathException

from bioshareX.utils import check_symlinks_dfs, find_symlink, is_realpath, path_contains, paths_contain, test_path, get_all_symlinks


def pkgen():
    import random
    import string
    return ''.join(random.choice(string.ascii_lowercase + string.digits) for x in range(15))

class ShareStats(models.Model):
    share = models.OneToOneField('Share',unique=True,related_name='stats', on_delete=models.CASCADE)
    num_files = models.IntegerField(default=0)
    bytes = models.BigIntegerField(default=0)
    updated = models.DateTimeField(null=True)
    def hr_size(self):
        from bioshareX.utils import sizeof_fmt
        return sizeof_fmt(self.bytes)
    def can_update(self, min_hours_since_update=1):
        min_hours_since_update = min_hours_since_update or 1 # template is passing in None so we aren't getting default
        if not self.updated or (((timezone.now() - self.updated).total_seconds() // 3600) > min_hours_since_update):
            return True
        return False
    def update_stats(self, min_hours_since_update=1):
        if not self.can_update(min_hours_since_update):
            return
        from bioshareX.utils import get_share_stats

        #         if self.updated is None:
        stats = get_share_stats(self.share)
#         self.num_files = stats['files']
        self.bytes = stats['size']
        self.updated = timezone.now()
        self.save()

class Filesystem(models.Model):
    TYPE_STANDARD = 'STANDARD'
    TYPE_ZFS = 'ZFS'
    TYPES = ((TYPE_STANDARD,'Standard'),(TYPE_ZFS,'ZFS'))
    name = models.CharField(max_length=50)
    description = models.TextField()
    path = models.CharField(max_length=200)
    users = models.ManyToManyField(User, related_name='filesystems')
    type = models.CharField(max_length=20,choices=TYPES,default=TYPE_STANDARD)
    def __str__(self):
        return '%s: %s' %(self.name, self.path)

class FilePath(models.Model):
    path = models.CharField(max_length=200)
    name = models.CharField(max_length=50,null=True,blank=True)
    description = models.TextField(null=True,blank=True)
    regexes = ArrayField(models.CharField(max_length=200), blank=False)
    users = models.ManyToManyField(User, related_name='file_paths', blank=True)
    show_path = models.BooleanField(default=False)
    def is_valid(self, path):
        if not path_contains(self.path, path):
            return False
        if not self.regexes or len(self.regexes) == 0:
            return True
        for regex in self.regexes:
            if re.match(regex, path):
                return True
        return False
    def __str__(self):
        return '%s: %s' %(self.name, self.path) if self.name else self.path

class Share(models.Model):
    id = models.CharField(max_length=15,primary_key=True,default=pkgen)
    slug = models.SlugField(max_length=50,blank=True,null=True)
    parent = models.ForeignKey('self',null=True,blank=True, on_delete=models.RESTRICT)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    owner = models.ForeignKey(User, on_delete=models.PROTECT)
    name = models.CharField(max_length=125)
    secure = models.BooleanField(default=True)
    read_only = models.BooleanField(default=False)
    locked = models.BooleanField(default=False)
    notes = models.TextField(null=True,blank=True)
    tags = models.ManyToManyField('Tag')
    link_to_path = models.CharField(max_length=200,blank=True,null=True)
    filepath = models.ForeignKey(FilePath,blank=True,null=True, on_delete=models.RESTRICT)
    sub_directory = models.CharField(max_length=200,blank=True,null=True)
    real_path = models.CharField(max_length=200,blank=True,null=True)
    filesystem = models.ForeignKey(Filesystem, on_delete=models.PROTECT)
    path_exists = models.BooleanField(default=True)
    symlinks_found = models.DateTimeField(null=True)
    illegal_path_found = models.DateTimeField(null=True)
    last_checked = models.DateTimeField(null=True)
    last_data_access = models.DateTimeField(null=True)
    meta = models.JSONField(default=dict)
    PERMISSION_VIEW = 'view_share_files'
    PERMISSION_DELETE = 'delete_share_files'
    PERMISSION_DOWNLOAD = 'download_share_files'
    PERMISSION_WRITE = 'write_to_share'
    PERMISSION_LINK_TO_PATH = 'link_to_path'
    PERMISSION_ADMIN = 'admin'
    PERMISSION_SHARE_READ_ONLY = 'share_read_only'
    def __str__(self):
        return self.name
    @property
    def slug_or_id(self):
        return self.slug if self.slug else self.id
    @staticmethod
    def get_by_slug_or_id(slug_or_id):
        return Share.objects.select_related('filesystem', 'filepath', 'owner').get(Q(id=slug_or_id)|Q(slug=slug_or_id))
    def update_last_modified(self,commit=True):
        self.updated = timezone.now()
        if commit:
            self.save()
    def get_url(self,subpath=None):
        if subpath:
            return reverse('list_directory',kwargs={'share':self.slug_or_id,'subpath':subpath})
        return reverse('list_directory',kwargs={'share':self.slug_or_id})
    def get_stats(self, min_hours_since_update=None):
        stats = ShareStats.objects.get_or_create(share=self)[0]
        stats.update_stats(min_hours_since_update=min_hours_since_update)
        return stats
    @staticmethod
    def user_queryset(user,include_stats=True):
        from guardian.shortcuts import get_objects_for_user
        shares = get_objects_for_user(user, 'bioshareX.view_share_files')
#         query = Q(id__in=[s.id for s in shares])|Q(owner=user) if user.is_authenticated else Q(id__in=[s.id for s in shares])
        query = Q(id__in=shares)|Q(owner=user) if user.is_authenticated else Q(id__in=shares)
        if include_stats:
            return Share.objects.select_related('stats').filter(query)
        else:
            return Share.objects.filter(query)
    #Get a list of users with ANY permission.  Useful for getting lists of emails, etc.
    def get_users_with_permissions(self):
        return list( 
             set(
                 [uop.user for uop in ShareUserObjectPermission.objects.filter(content_object=self).select_related('user')] +
                 list(User.objects.filter(groups__in=ShareGroupObjectPermission.objects.filter(content_object=self).values_list('group_id',flat=True)))
                 )
             )
    @cached_property
    def share_permissions(self):
        from .permissions import SharePermissions
        return SharePermissions(self)
    def get_permissions(self,user_specific=False):
        return self.share_permissions.get_permissions(user_specific)
    def get_user_permissions(self,user,user_specific=False):
        return self.share_permissions.get_user_permissions(user, user_specific)
    def get_all_user_permissions(self,user_specific=False):
        return self.share_permissions.get_all_user_permissions(user_specific)
    def get_path(self):
        return os.path.join(self.filesystem.path,self.id)
    def get_link_path(self, add_trailing_slash=True):
        if self.link_to_path and add_trailing_slash:
            return os.path.join(self.link_to_path, '')
        return None
    def get_subshare_link_path(self):
        if self.parent:
            return os.path.join(self.parent.get_path(), self.sub_directory)
    def get_zfs_path(self):
        if not getattr(settings,'ZFS_BASE',False) or not self.filesystem.type == Filesystem.TYPE_ZFS:
            return None
        return os.path.join(settings.ZFS_BASE,self.id)
    def get_realpath(self):
        return os.path.realpath(self.get_path())
    def check_path(self,subdir=None):
        path = self.get_path()
        if subdir:
            path = os.path.join(path,subdir)
        return os.path.exists(path)
    def get_removed_path(self):
        return os.path.join(settings.REMOVED_FILES_ROOT,self.id)
    def get_path_type(self,subpath):
        full_path = os.path.join(self.get_path(),subpath)
        if os.path.isfile(full_path):
            return 'file'
        elif os.path.isdir(full_path):
            return 'directory'
        else:
            return None
    def create_folder(self,name,subdir=None):
        os.umask(settings.UMASK)
        path = self.get_path() if subdir is None else os.path.join(self.get_path(),subdir)
        if os.path.exists(path):
            folder_path = os.path.join(path,name)
            if not os.path.exists(folder_path):
                os.makedirs(folder_path)
            else:
                raise IllegalPathException('Unable to create directory, path already exists.')
        return folder_path
    def delete_path(self,subpath):
        import shutil
        if subpath is None or subpath == '' or subpath.count('..') != 0:
            return False
        path = os.path.join(self.get_path(),subpath)
        if os.path.exists(path):
            if os.path.isfile(path):
                os.remove(path)
                return True
            elif os.path.isdir(path):
                shutil.rmtree(path)
                return True
        return False
    def add_tags(self,tags,save=True):
        tag_list = []
        for tag in tags:
            tag = tag.strip()
            if len(tag) > 2 :
                tag_list.append(Tag.objects.get_or_create(name=tag)[0])
        self.tags.set(tag_list)
        if save:

templates/share/delete_share.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Hello World!{% endblock %}

{% block content %}
  {%if message%}
  <h2>{{message}}</h2>
  {% endif %}
  {%if show_confirm%}
  <h3>Are you absolutely sure you want to delete "{{share.name}}"?  {% if share.link_to_path %}After deleting the share, the symlink will be removed, but the data will remain.{% else %}All files will be lost.{% endif %}</h3>
  <a href="{% url 'confirm_delete_share' share.id %}" class="btn btn-danger">Yes, Delete it!</a>
  {% endif %}
{% endblock %}

templates/share/edit_share.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <p>
  <form class="form-horizontal" method="POST" action="#">
  <fieldset>
	  <legend>Edit Share</legend>
	    {{ form|crispy }}
	  <div class="control-group">
	    <div class="controls">
	    	<button type="submit" class="btn">Edit</button>
	    </div>
	  </div>
  </fieldset>
  {% csrf_token %}
  </form>
  </p>
{% endblock %}

templates/share/links.html
{% extends "base.html" %}
{% load static %}
{% load compress %}
{% block title %}{{title}}{% endblock %}
{% block head %}
{{block.super}}
<link rel="stylesheet" type="text/css" href="{% static "lib/datatables/datatables.min.css" %}"/>
{% endblock %}
{% block content %}
  {% if not share.locked %}
  <h2><a href="{% url 'list_directory' share.id %}">{{share.name}} ({{share.id}})</a> Symlinks</h2>
  <div class="alert alert-warning">
    Last checked: {{share.last_checked}}
    <br>Symlinks found: {{share.symlinks_found}}
    {% if share.illegal_path_found %}
    <br>Illegal path found: {{share.illegal_path_found}}
    {% endif %}
  </div>
  {% else %}
  <h2>{{share.name}} ({{share.id}})</a> Locked</h2>
  <div class="alert alert-danger">
    Locked: {{share.locked}} 
    {% if user.is_superuser and not share.illegal_path_found %}
    <a class="btn btn-danger" href="{% url 'unlock' share=share.id %}">Unlock</a>
    {% endif %}
    <br>Last checked: {{share.last_checked}}
    <br>Symlinks found: {{share.symlinks_found}}
    {% if share.illegal_path_found %}
    <br>Illegal path found: {{share.illegal_path_found}}
    {% endif %}
  </div>
  {% endif %}
    <h3>Symlinks</h3>
    {% if user == share.owner or user.is_superuser%}
      <table class="table table-striped table-condensed" id="link-table">
        <thead><tr><th>Source</th><th>Destination</th><th>Depth</th><th>Warning</th><th>Error</th></tr></thead>
        <tbody>
        {% for link in symlinks %}
          <tr><td>{{link.path}}</td><td>{% if link.warning or link.error %}<b><i class="icon-warning-sign"></i>{{link.target}}</b>{% else %}{{link.target}}{% endif %}</td><td>{{link.depth}}</td><td class="text-warning">{% if link.warning %}{{link.warning}}{% endif %}</td><td class="text-error">{% if link.error %}{{link.error}}{% endif %}</td></tr>
        {% endfor %}
        </tbody>
      </table>
    {% else %}
      <h4>Only the share's owner is allowed to view symlinks</h4>
    {% endif %}
  <h3>Logs</h3>
  {% include 'share/logs.html' %}
{% endblock %}
{% block scripts %}
<script type="text/javascript" src="{% static "lib/datatables/datatables.min.js" %}"></script>
{{block.super}}
<script>
  /* Table initialisation */
  $(document).ready(function() {
    var filetable = $('#link-table').dataTable( {
      "bPaginate": false,
      "oLanguage": {
        "sLengthMenu": "_MENU_ records per page"
      },
      "aoColumns": [
                      {bSortable: true},
                      {bSortable: true},
                      {bSortable: true},
                      {bSortable: true},
                      {bSortable: true}
                  ],
      "oLanguage": {
             "sSearch": "Filter:"
           }
    } );
    filetable.fnSort([[0,"asc"]]);
  } );
</script>
{% compress js %}
<script src="{% static "js/services/ng-table-services.js" %}"></script>
<script src="{% static "js/controllers/share-controller.js" %}"></script>
{% endcompress %}
{% endblock%}

templates/share/logs.html
<div class="tab-pane" id="log-tab">
    <div ng-controller="LogController" ng-init="init('{{share.id}}')">
    {% verbatim %}
     <table ng-table="tableParams" class="limit-col-width table table-bordered table-striped table-condensed" style="max-width:600px !important;">
      <tr ng-repeat="row in $data track by row.id">
        <td data-title="'Timestamp'" sortable="'timestamp'">{{row.timestamp | date : 'short'}}</td>
        <td data-title="'Action'" filter="{action__icontains: 'text'}" sortable="'action'">{{row.action}}</td>
        <td data-title="'User'" filter="{user__username__icontains: 'text'}" sortable="'user__username'">{{row.user.username}}</td>
        <td data-title="'Text'" filter="{text__icontains: 'text'}" sortable="'text'"><p title="{{row.text}}">{{row.text}}</p></td>
        <td data-title="'Paths'" filter="{paths__icontains: 'text'}"><p ng-repeat="path in row.paths" title="{{path}}">{{path}}</p></td>
      </tr>
    </table>
    {% endverbatim %}
    </div>
</div>

templates/share/new_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Hello World!{% endblock %}

{% block content %}
  <p>
  <form class="form-horizontal" method="POST" action="#">
  <fieldset>
	  <legend>Create a New Share</legend>
	    {{ form|crispy }}
	  <div class="control-group">
	    <div class="controls">
	    	<button type="submit" class="btn">Create</button>
	    </div>
	  </div>
  </fieldset>
  {% csrf_token %}
  </form>
  </p>
{% endblock %}

templates/share/new_share.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Create a share{% endblock %}

{% block content %}
  <p>
  <form class="form-horizontal" method="POST" action="#">
  <fieldset>
	  <legend>Create a new Share{% if group %} for group "{{group}}"{% endif %}</legend>
	  {% if share %}
	  	<p>
		  	This will create a new share from the '{{subdir}}' directory from the <a href="{% url 'list_directory' share.slug_or_id %}">{{share.name}}</a> share.
		  	Please note that any file changes in this share will be reflected in the original share, and vice-versa.  
		  	Permissions assigned for each share will only effect access to the files accessible from that share. 
	  	</p>
	  {% endif %}
	  {% if error %}<h3>Exception: {{error}}</h3>{% endif %}
	    {{ form|crispy }}
	  <div class="control-group">
	    <div class="controls">
	    	<button type="submit" class="btn">Create</button>
	    </div>
	  </div>
  </fieldset>
  {% csrf_token %}
  </form>
  </p>
{% endblock %}

templates/share/permissions.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load guardian_tags %}
{% load compress %}
{% block title %}Permissions: {{share.name}}{% endblock %}

{% block content %}
<style>
.verticalText
{
text-align: center;
vertical-align: middle;
width: 20px;
margin: 0px;
padding: 0px;
padding-left: 3px;
padding-right: 3px;
padding-top: 10px;
white-space: nowrap;
-webkit-transform: rotate(-90deg);
-moz-transform: rotate(-90deg);
}
table.permissions{
margin-top: 50px;
}
table.permissions tr td{
border: thin solid #ccc;
text-align:center;
}
table.permissions tr td:first-child{
text-align: left;
}
table.permissions tr td input{
margin:0px;
}
table.permissions tr.modified{
background-color:yellow;
}
</style>

<h1>Permissions: <a href="{% url 'list_directory' share.slug_or_id %}">{{share.name}}</a></h1>
<div class="row">
  <div class="span5">
    <legend>General Settings</legend>
 	<label class="checkbox" data-toggle="tooltip" title="If this is not selected, anyone with the URL may view or download files."><input id="secure" type="checkbox" {% if share.secure %}checked{%endif%}/>Secure share</label>
  	<button class="btn" id="updateGeneralSettings">Update</button>
  </p>

 <legend>Permissions</legend>
 <textarea id="addUser" class="no-margin" type="text" placeholder="joe@example.com, susan@example.com, ..." style="width:400px;height:100px;"></textarea><br><button id="addUserButton" class="btn">Add</button>

<div id="user-permission-section" style="display:none">
	<table id="user_permissions" class="permissions">
	<thead>
	<tr><th>User</th><th><div class="verticalText">Browse</div></th><th><div class="verticalText">Download</div></th>{% if not share.read_only %}<th><div class="verticalText">Write</div></th><th><div class="verticalText">Delete</div></th>{% endif %}<th><div class="verticalText">Share</div></th><th><div class="verticalText">Administer</div></th><th></th></tr>
	</thead>
	<tbody>
	<!-- <tr><td>Username</td><td><input type="checkbox"></td><td><input type="checkbox"></td><td><input type="checkbox"></td></tr> -->
	</tbody>
	</table>
	<label class="checkbox" data-toggle="tooltip" title="Email users who previously had no permissions.  Users who already had permissions will not be emailed.  Newly created accounts will receive emails regardless of this setting."><input id="email_users" type="checkbox" checked/>Send email</label>
	<button class="btn" id="updateUserPermissions">Update</button>
</div>
 
</div>
  <div class="span7"><div id="messages"></div></div>
</div>
{% endblock %}

{% block scripts %}
{{block.super}}
<script>
var get_permissions_url = '{% url 'api_get_permissions' share=share.id %}';
var set_permissions_url = '{% url 'api_set_permissions' share=share.id %}';
var share_with_url = '{% url 'api_share_with' share=share.id %}';
var get_group_url = '{% url 'api_get_group' %}';
var update_share_url = '{% url 'api_update_share' share=share.id %}'; 
var read_only = {% if share.read_only %}true{% else %}false{% endif %};

</script>
{% compress js %}
<script src="{% static "lib/textcomplete/jquery.textcomplete.js" %}"></script>
<script src="{% static "js/share/permissions.js" %}"></script>
{% endcompress %}
{% endblock %}

templates/share/shares.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load guardian_tags %}
{% load compress %}
{% block title %}Shares{% endblock %}
{% block content %}
{% if group %}
	{% get_obj_perms request.user for group as "group_permissions" %}
	<h2>{{group}}
   	<div class="pull-right">
	   	{% if request.user.is_staff or 'manage_group' in group_permissions %}
	   	<a href="{% url 'manage_group' group_id=group.id %}" class="btn btn-small ptn-primary">Manage group</a>
	   	{% endif %}
	</div>
	</h2>
	<h4>Users</h4>
	<p>{% for u in group.user_set.all %}{{u}}{% if not forloop.last%}, {% endif %}{% endfor %}</p>
	<h3>Shares</h3>
{% else %}
<h2>Shares</h2>
{% endif %}

{% if locked %}
<h3>The following shares are locked. View <a href="{% url 'home' %}">all shares.</a></h3>
{% endif %}
{% if bad_paths %}
<h3>The following shares have non existent paths. View <a href="{% url 'home' %}">all shares.</a></h3>
{% endif %}
{% if group %}
	{% if 'add_share' in request.user.permissions or request.user.is_superuser %}
		<a href="{% url 'create_group_share' group_id=group.id %}">Create</a> a new share for "{{group}}"
	{% endif %}
{% endif %}

 <div ng-controller="SharesController" ng-init="init({ {% if locked %}locked:true,{% endif %}{% if bad_paths %}path_exists:false,{% endif %}{% if group %}group:'{{group.name}}'{% endif %}})" ng-cloak>
	    {% verbatim %}
	    	<h4>Fields</h4>
            <div style="margin-bottom: 20px">
		        <label class="checkbox-inline" ng-repeat="(col,val) in cols">
		          <input type="checkbox" ng-model-options="{ getterSetter: true }" ng-model="cols[col]"/> {{col}}
		        </label>
		      </div>
			{% endverbatim %}
			{% if user.share_set.all.count > 0 %}
			<!-- If a user owns any shares, give them the advanced filters -->
			{% verbatim %}
			<h4>
				<a class="pointer" ng-if="!show_filters" ng-click="toggleFilters()">Show</a>
				<a class="pointer" ng-if="show_filters" ng-click="toggleFilters()">Hide</a>
				Advanced Filters
			</h4>
			<div style="margin-bottom: 20px" ng-show="show_filters">
				<!-- <label class="checkbox-inline" ng-repeat="(filter,label) in filter_labels" ng-click="setFilter(filter, filters[filter]);saveState()"> -->
				<label class="checkbox-inline" ng-repeat="(filter,label) in filter_labels">
					<input type="checkbox" ng-model-options="{ getterSetter: true }" ng-model="filters[filter]"/> {{filter_labels[filter]}}
				</label>
				<label title="Only show shares containing symlinks with a target containing a string.">Symlink target contains 
					<input ng-model="filters['symlink_target']"/>
				</label>
				<button class="btn" ng-click="setAllFilters();">Update</button>
			</div>
			{% endverbatim %}
			{% endif %}
			{% verbatim %}
	     <table ng-table="tableParams" class="limit-col-width table table-bordered table-striped table-condensed">
	      <tr ng-repeat="row in $data track by row.id">
	        <td ng-if="cols['Share']" data-title="'Share'" filter="{name__icontains: 'text'}" sortable="'name'">
				<a ng-click="saveState()" ng-if="row.path_exists && !row.locked" href="{{row.url}}">{{row.name}}</a>
				<span ng-if="!row.path_exists" class="error" title="Share has non existant path">{{row.name}}</span>
				<a ng-click="saveState()" ng-if="row.locked && row.path_exists" href="{{row.url}}" class="error" title="Share has been locked."><i class="icon-lock"></i> {{row.name}}</a>
			</td>
	        <td ng-if="cols['Description']" data-title="'Description'" filter="{notes__icontains: 'text'}">{{row.notes}}</td>
	        <td ng-if="cols['Tags']" data-title="'Tags'" filter="{tags: 'text'}"><span ng-repeat="tag in row.tags"><a class="pointer" ng-click="setFilter('tags',tag.name)">{{tag.name}}</a>{{$last ? '' : ', '}}</span></td>
	        <td ng-if="cols['Owner']" data-title="'Owner'" filter="{owner__username__icontains: 'text'}" sortable="'owner__username'"><a class="pointer" ng-click="setFilter('owner__username__icontains',row.owner.username)">{{row.owner.username}}</a></td>
	        <td ng-if="cols['Users']" data-title="'Users'" filter="{user: 'text'}"><span ng-repeat="u in row.users"><a class="pointer" ng-click="setFilter('user',u)">{{u}}</a>{{$last ? '' : ', '}}</span></td>
	        <td ng-if="cols['Groups']" data-title="'Groups'" {% if not group %}filter="{group: 'text'}"{% endif %}><span ng-repeat="g in row.groups"><a class="pointer" ng-click="setFilter('group',g)">{{g}}</a>{{$last ? '' : ', '}}</span></td>
	        <td ng-if="cols['Created']" data-title="'Created'" sortable="'created'">{{row.created | date : 'short'}}</td>
	        <td ng-if="cols['Modified']" data-title="'Modified'" sortable="'updated'">{{row.updated | date : 'short'}}</td>
	        <td ng-if="cols['Files']" data-title="'Files*'" sortable="'stats__num_files'">{{row.stats.num_files}}</td>
	        <td ng-if="cols['Size']" data-title="'Size*'" sortable="'stats__bytes'">{{row.stats.bytes | bytes}}</td>
	      </tr>
	    </table>
	    {% endverbatim %}
</div>
<p>
{{total_size}} of storage being used by {% if group%}{{group}}{% else %}{{request.user.username}}{% endif %}.*
</p>
*Files statistics updated daily.
<p><a href="/bioshare/api/shares/export/?ordering=-updated" class="btn btn-primary" title="Export share table">Export</a></p>
{% endblock %}

{% block scripts %}
{{block.super}}
{% compress js %}
<script src="{% static "js/services/ng-table-services.js" %}"></script>
<script src="{% static "js/controllers/shares-controller.js" %}"></script>
{% endcompress %}


{% endblock %}